### PR TITLE
Feature/ods library type - for master

### PR DESCRIPTION
**Pull request by clemensutschig**
Addition of a new component type (ods-library).

This type will
-  only build in dev
-  no TIP / TIR

### CODE REVIEW

**Comment by clemensutschig** [comment]
I talked with QA (Belen) about this - and agreed, no TIR :) so I think that's it then ...

**Comment by clemensutschig** [comment]
@metmajer ping? 🗡️

**Comment by metmajer** [comment]
Nice work @clemensutschig ! Where are the JenkinsService changes coming from?

**Comment by clemensutschig** [comment]
I finally managed to reactor this beast and use the Jenkins native API

**Comment by metmajer** [comment]
Got it. Suggestion is to have this in a separate PR.

**Review by metmajer — APPROVED** [review]

**Pull request merged**
