### PR TITLE
Enable automated Document Version for Jira Projects

### PR DESCRIPTION
**Pull request by martsec**
Versioning feature allows the applications to create documents with only subsets of Jira issues, allowi to build one version on top of another. 

It will also show Images and more format (e.g. tables or bullet points) in Requirements and TechSpecs from Jira. 

This affects mainly orchestration Project and LeVADocumentUseCase

Also, This contains a lot of codenarc improvements. 

Will require a new '1.1' version of https://github.com/opendevstack/ods-document-generation-templates 

Related to #415

### CODE REVIEW

**Comment by martsec** [comment]
This is ready for review @jorge-romero @metmajer

**Comment by clemensutschig** [comment]
Whats the status of this?

**Comment by metmajer** [comment]
@clemensutschig We are working on this for the upcoming EDP 1.1 release. Automated tests missing and being worked on.

**Comment by metmajer** [comment]
@jafarre-viewnext @martsec the merge was not undone as it seems...

**Comment by metmajer** [comment]
@jafarre-viewnext @jorge-romero it seems like the merge commit was removed again from 3.x, but this PR shows as merged. Will you open a new PR?

**Comment by stitakis** [comment]
@metmajer @martsec @jorge-romero @jafarre-viewnext I have opened a new PR -> #508 (https://github.com/opendevstack/ods-jenkins-shared-library/pull/508)

**Pull request merged**
