### PR TITLE
add init hook for ods-test components - master

### LINKED ISSUE #699: Provide init hook for test quickstarters to better plug into RM
**Is your feature request related to a problem? Please describe.**
For some quickstarters - like tosca - we want to retrieve external files early in the process, before we build, and only in specific cases - and to commit them to the repository. This is currently not possible.

**Describe the solution you'd like**
a hook in the init phase of the MRO

### PR DESCRIPTION
**Pull request by clemensutschig**
closes #699  for master

@segator here we go :)

### CODE REVIEW

**Comment by clemensutschig** [comment]
@metmajer @segator  - I just tested it locally - seems to work :)

(this also contaisn a SUPER important bug fix) ...

**Comment by clemensutschig** [comment]
maybe we should do the add / commit etc in the framework ... @metmajer  @michaelsauter  ... thoughts?

**Comment by clemensutschig** [comment]
the more I play with it - the more I think we could actually put that magic into the shared lib - and enable with a flag? ..

**Comment by clemensutschig** [comment]
> the more I play with it - the more I think we could actually put that commit / push magic into the component shared lib - and enable with a flag? ..

**Comment by clemensutschig** [comment]
super weird .. the re-checkout works .. 
git log -1
```
+ pwd
/var/lib/jenkins/jobs/tosstst-cd/jobs/tosstst-cd-release-master/workspace/repositories/tosca
+ git log -1
commit **747a95a1394a6cb86864adfc901f8d2821ec53e1**
Author: ODS Jenkins Shared Library System User <undefined>
Date:   Thu Aug 5 18:09:34 2021 +0000

    test
+ ls
Init.Jenkinsfile
Jenkinsfile
metadata.yml
README.md
release-manager.yml
src
test
tosca-acceptance.json
tosca-installation.json
tosca-integration.json
[Pipeline] }
[Pipeline] // dir
```

while the git data (from scm) is wrong (the old original commit):
```
[Pipeline] echo
DEBUG: new git data for tosca: [branch:master, commit:**7a0bb20ae4c8fc1e385684cf157ef3867e29289e**, previousCommit:9c2bd2f148140e76309e2f489b5dfc8172a9ce95, previousSucessfulCommit:a2684f614e62c2805adb5377349cc0a861b2cb83, 
``` 

@michaelsauter  I am really lost here ... any ideas?

**Comment by clemensutschig** [comment]
I tried now with a hack .. https://github.com/opendevstack/ods-jenkins-shared-library/pull/700/commits/8bb16a7e8b94cfdd0a3bcf61dba1b82bb8d769c3#diff-55f4d88db8a0231e16b742f7cfa56fc9e61797bcf2b6dc2ca2ce20c0f7aedcfcR265

**Comment by clemensutschig** [comment]
@segator cool?

**Comment by clemensutschig** [comment]
ping?

**Review by segator — APPROVED** [review]

**Comment by metmajer** [comment]
@clemensutschig @segator I want to include this in a micro-change, together with the updated Tosca Quickstarter, after the release of ODS 4.0. No merging into 4.x at this point in time please, so we can thoroughly test this in isolation.

**Comment by segator** [comment]
So you want a cherrypick to 3.x?

**Comment by clemensutschig** [comment]
@segator nope - we will cherrypick into 4.x after the release of 4.x

**Comment by clemensutschig** [comment]
@metmajer - there is a critical fix in there as well - in the MRO for a missing `name ==` - this you folks should take

**Comment by metmajer** [comment]
@clemensutschig if you cannot create a PR for a fix of 4.x, can you please advise @jafarre-viewnext on what to do?

**Comment by clemensutschig** [comment]
@metmajer see https://github.com/opendevstack/ods-jenkins-shared-library/pull/710/files

**Pull request merged**
