### PR TITLE
Clarify repository types

### PR DESCRIPTION
**Pull request by serverhorror**
Introduces edits in the master branch of ODS

### CODE REVIEW

**Comment by serverhorror** [comment]
In reference to #459

**Comment by michaelsauter** [comment]
@serverhorror Could you update this PR to only include the changes introduced by 719bee2? Otherwise I think this will break stuff ... (the alias thingy in the docs)

**Comment by metmajer** [comment]
@serverhorror agree with Michael that this PR contains too many changes. May I ask you about the use-case? What was the need to switch to the ods-service type? Did this component contain code?

**Comment by serverhorror** [comment]
@michaelsauter  When you rely on to magic from the IDE... sorry about that. This should have been only the cherry-pick from #459. I think that's better now.

fix #458

**Comment by serverhorror** [comment]
@metmajer There's nothing that could be unit tested here. No code just pulling in an image and adapting it so that the clients requirements are met (e.g. one is unable to roll-out images directly from the upsream repository).

**Comment by metmajer** [comment]
@serverhorror we should consider the necessity that code components have to provide Unit tests (at least in our enterprise context). This is why the pipeline fails. A general recommendation to use the `ods-service` type is misleading. Let's keep this PR open and add an improved description.

**Comment by serverhorror** [comment]
@metmajer Your call. Just be aware that it already is in ODS3. Best to close this PR, revert #459 and reopen #458 then.

Just keep in mind that, while a noble goal, not everything can (or should be *unit* tested). Yes, there are regulatory requirements and they do make sense. It is, however, not the case for all parts of all organizations and this simply documents the current state.

**Review by michaelsauter — APPROVED** [review]

**Comment by michaelsauter** [comment]
I would be fine with the addition.

**Comment by metmajer** [comment]
Fine, too. Let's not overcomplicate things. Compliance related information should not be handled here.

**Pull request merged**
