### PR TITLE
Retry params bc

### LINKED ISSUE #901: Add retry configurable for the Openshift image build stage
**Is your feature request related to a problem?**
Sometimes the build pod in Openshift does not get to completed state in the 1 min we currently have for this process -> [code](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/OpenShiftService.groovy#L320-L337)

**Describe the solution you'd like**
Set up a retry configurable by parameters in the Openshift build stage similar to what we did for the deployment process #465

@metmajer

### PR DESCRIPTION
**Pull request by braisvq1996**
closes #901 
@metmajer @tbugfinder

### CODE REVIEW

**Comment by braisvq1996** [comment]
The code should work but I have not test it yet, I will do it before merging it

**Comment by braisvq1996** [comment]
It is working properly for Component and Orchestration pipeline

**Review by gerardcl — APPROVED** [review]
LGTM! 🚀

**Comment by braisvq1996** [comment]
I will prepare 4.x PR

**Pull request merged**
