### PR TITLE
(component / bbservice) synchronize block - for create token - 3.x

### LINKED ISSUE #576: Bitbucket status update for repos sometimes fails in concurrent situations
**Describe the bug**
3+ concurrent repositories - built for the first time thru the release manager - (may fail) on setting bitbucket status .. see logs

**Expected behavior**
no error, retry until works

**Affected version (please complete the following information):**
 - OpenDevStack [3.x / master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
nning on pod-8ab51dc6-efef-4b09-aded-d7bdee69212a-hgn8m-h0trw in /tmp/workspace/ofi0202-cd/ofi0202-cd-release-master
[Pipeline] {
[Pipeline] echo
DEBUG: [pod-8ab51dc6-efef-4b09-aded-d7bdee69212a]  (took 25650 ms)
[Pipeline] echo
DEBUG: [buildstatus-ffce0fb3-INPROGRESS] Setting Bitbucket build status to 'INPROGRESS' on commit 'ffce0fb3e1eaf111452621641892523432d5ba42' / 'https://jenkins-/job/ofi0202-cd/job/ofi0202-cd-release-master/9/'
[Pipeline] withCredentials
[Pipeline] // withCredentials
[Pipeline] echo
Secret cd-user-bitbucket-token does not exist yet, it will be created now.
[Pipeline] withCredentials
Masking supported pattern matches of $USERNAME or $PASSWORD
[Pipeline] {
[Pipeline] echo
Requesting token via PUT some.bitbucket.x/rest/access-tokens/1.0/users/**** with payload={"name": "ods-jenkins-shared-library-ofi0202-cd", "permissions": ["PROJECT_WRITE", "REPO_WRITE"]}
[Pipeline] sh
Running on pod-3fcad60c-90e4-4d83-a036-66f06ecfc077-gs362-ww2s5 in /tmp/workspace/ofi0202-cd/ofi0202-cd-release-master
[Pipeline] {
[Pipeline] echo
DEBUG: [pod-3fcad60c-90e4-4d83-a036-66f06ecfc077]  (took 29029 ms)
[Pipeline] echo
DEBUG: [buildstatus-10c815db-INPROGRESS] Setting Bitbucket build status to 'INPROGRESS' on commit '10c815db29b4ee06b3f90d530c7800b768e44134' /'https://jenkins-/job/ofi0202-cd/job/ofi0202-cd-release-master/9/'
[Pipeline] withCredentials
[Pipeline] // withCredentials
[Pipeline] echo
Secret cd-user-bitbucket-token does not exist yet, it will be created now.
[Pipeline] withCredentials
Masking supported pattern matches of $USERNAME or $PASSWORD
+ curl --silent --fail --show-error --request PUT --header 'Content-Type: application/json' --header 'Authorization: Basic notshownpw=' --data '{"name": "ods-jenkins-shared-library-ofi0202-cd", "permissions": ["PROJECT_WRITE", "REPO_WRITE"]}' some.bitbucket.x/rest/access-tokens/1.0/users/****
[Pipeline] {
[Pipeline] echo
Requesting token via PUT some.bitbucket.x/rest/access-tokens/1.0/users/**** with payload={"name": "ods-jenkins-shared-library-ofi0202-cd", "permissions": ["PROJECT_WRITE", "REPO_WRITE"]}
[Pipeline] sh
curl: (22) The requested URL returned error: 403 
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] stage
[Pipeline] { (odsPipeline error)
[Pipeline] echo
WARN: [thesecond] ***** Finished ODS Pipeline for thesecond (with error) ***** (took 49671 ms)
[Pipeline] echo
WARN: Error: hudson.AbortException: script returned exit code 22
[Pipeline] echo
DEBUG: [buildstatus-ffce0fb3-FAILED] Setting Bitbucket build status to 'FAILED' on commit 'ffce0fb3e1eaf111452621641892523432d5ba42' / 'https://jenkins-/ofi0202-cd-release-master/9/'
[Pipeline] withCredentials
[Pipeline] // withCredentials
+ curl --silent --fail --show-error --request PUT --header 'Content-Type: application/json' --header 'Authorization: Basic notshownpw=' --data '{"name": "ods-jenkins-shared-library-ofi0202-cd", "permissions": ["PROJECT_WRITE", "REPO_WRITE"]}' some.bitbucket.x/rest/access-tokens/1.0/users/****
[Pipeline] echo
Secret cd-user-bitbucket-token does not exist yet, it will be created now.
[Pipeline] withCredentials
Masking supported pattern matches of $USERNAME or $PASSWORD
[Pipeline] {
[Pipeline] echo
Requesting token via PUT some.bitbucket.x/rest/access-tokens/1.0/users/**** with payload={"name": "ods-jenkins-shared-library-ofi0202-cd", "permissions": ["PROJECT_WRITE", "REPO_WRITE"]}
[Pipeline] sh
curl: (22) The requested URL returned error: 403 
[Pipeline] }
[Pipeline] // withCredentials
```

**Additional context**
the culprit is here:
https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/BitbucketService.groovy#L286-L292

withTokenCredentials fails - but outside of the try / retry logic ..

### PR DESCRIPTION
**Pull request by clemensutschig**
closes #576 for 3.x

### CODE REVIEW

**Comment by clemensutschig** [comment]
@felipecruz91  - please provide feedback on this

**Review by michaelsauter — APPROVED** [review]
From what I understand, the should work so 👍 from my side.

**Comment by felipecruz91** [comment]
@clemensutschig @michaelsauter Given that the root cause was a limit in the number of Bitbucket tokens, we don't need to deploy this change, right?

**Comment by clemensutschig** [comment]
I think deploying it will allow to diagnose sth like this easier .. your call - it's in master already

**Comment by michaelsauter** [comment]
This might avoid multiple tokens being created, so probably good to have this in addition to the error messages.

**Pull request merged**
