### PR TITLE
Fix Document History in TIR and IVR is not correct after de deploy to P

### PR DESCRIPTION
**Pull request by jafarre-viewnext**

### CODE REVIEW

**Comment by clemensutschig** [comment]
@jafarre-viewnext  - I checked the code briefly .. and we do stuff (at least search for it - depending on the env type) - maybe that's a clue?

```
            def latestValidVersionId = this.getLatestDocVersionId(documentType, [environment])
            def docHistory = new DocumentHistory(this.steps, new Logger(this.steps, false), environment, documentName)
            def docChapters = this.project.getDocumentChaptersForDocument(documentType)
            def docChapterKeys = computeDocChaptersKeys(docChapters)
```

**Comment by jafarre-viewnext** [comment]
> @jafarre-viewnext - I checked the code briefly .. and we do stuff (at least search for it - depending on the env type) - maybe that's a clue?
> 
> ```
>             def latestValidVersionId = this.getLatestDocVersionId(documentType, [environment])
>             def docHistory = new DocumentHistory(this.steps, new Logger(this.steps, false), environment, documentName)
>             def docChapters = this.project.getDocumentChaptersForDocument(documentType)
>             def docChapterKeys = computeDocChaptersKeys(docChapters)
> ```

Yes, @clemensutschig , thanks a lot for your help! Actually, that's the base of the fix I have developed. I can't find, yet, an explanation on why the fix seems to be ignored.

**Comment by clemensutschig** [comment]
@jafarre-viewnext  -- does the fix work?

**Comment by jafarre-viewnext** [comment]
> @jafarre-viewnext -- does the fix work?
> 
> I am wondering if the re-integratioh of the branch (after deploy to P) - misses sth, or alike? and that is why we have the problem?

@clemensutschig I found the problem that prevented the fix from working. Now in my tests is working fine. There are also unit tests.

**Review by metmajer — APPROVED** [review]
👍

**Comment by clemensutschig** [comment]
We need a forward Port to master

**Pull request merged**
