### PR TITLE
proposal to fix file uploads when repositoryTipe is 'pipy'

### PR DESCRIPTION
**Pull request by jchaves**
We finally managed to put together a working example of minimal changes needed to correct the situation we detected.

Hopefully this should work without interfering with anything else.

### CODE REVIEW

**Comment by jchaves** [comment]
Hopefully would fix https://github.com/opendevstack/ods-jenkins-shared-library/issues/785

**Comment by clemensutschig** [comment]
very cool @jchaves  - did you test it? .. then I'll merge

**Comment by jchaves** [comment]
We can confirm, it's been tested and working. The user has been using code from my fork for a couple weeks now, so it should be ok :)

**Comment by clemensutschig** [comment]
can you please see if 4.x / and master contain the same problem?

**Comment by jchaves** [comment]
Hi @clemensutschig , we just did a couple of tests and, indeed, the problem is present on 4.x.

I'll open a new PR for this 4.x branch

Cheers!

**Pull request merged**
