### PR TITLE
Remove the workaround for NPE resolving issues

### PR DESCRIPTION
**Pull request by jafarre-viewnext**
issues

### CODE REVIEW

**Review by metmajer — DISMISSED** [review]
Thanks @jafarre-viewnext. Please wait until @s2oBCN has merged the new test cases to verify the correct behavior of this change.

**Comment by jafarre-viewnext** [comment]
> Thanks @jafarre-viewnext. Please wait until @s2oBCN has merged the new test cases to verify the correct behavior of this change.

Yes, I'll wait. It also needs to be in sync with the corresponding change in the plugin.

**Comment by metmajer** [comment]
@jafarre-viewnext you ping when you need something )

**Comment by metmajer** [comment]
@jafarre-viewnext is this still something you want to merge? Let's please close either way. Thanks!

**Comment by jafarre-viewnext** [comment]
> @jafarre-viewnext is this still something you want to merge? Let's please close either way. Thanks!

@metmajer Yes, this was pending having the test framework by @s2oBCN , but it can be merged any time.

**Comment by jafarre-viewnext** [comment]
The corresponding change to the plugin has already been merged. Should I merge this one, too?

**Review by metmajer — APPROVED** [review]

**Pull request merged**
