### PR TITLE
deploy: add configuration for pod findretry - master

### LINKED ISSUE #465: allow parameters for timeout and retries for getPodDataForDeployment(String rc)
There are cases when the transition from an image to a container might take longer than the hardcoded 5 times 12 seconds retries.
Therefore it would make sense to keep the default 5 times 12 seconds (=60s) delay initially however it should be configurable within a pipeline definition.

https://github.com/opendevstack/ods-jenkins-shared-library/blob/0d49d03b77042a39ce364a7ce5150af5504972a4/src/org/ods/services/OpenShiftService.groovy#L433-L446

```
.....
[Pipeline] echo
2020-10-01 02:49:35Z Could not find 'running' pod for deployment=xxxxxxxxxxxxxxxxxx - waiting
[Pipeline] sleep
Sleeping for 12 sec
[Pipeline] }
[Pipeline] // stage
.........
.........
[Pipeline] End of Pipeline
java.lang.RuntimeException: Could not find 'running' pod for deployment=myproject-32
	at org.ods.services.OpenShiftService.getPodDataForDeployment(OpenShiftService.groovy:445)
	at org.ods.component.RolloutOpenShiftDeploymentStage.run(RolloutOpenShiftDeploymentStage.groovy:117)
	at org.ods.component.Stage.execute(Stage.groovy:23)
```

### PR DESCRIPTION
**Pull request by clemensutschig**
closes #465 for master

### CODE REVIEW

**Comment by clemensutschig** [comment]
@serverhorror - I also added the `testResults` flag to the doc :)

**Review by michaelsauter — APPROVED** [review]
Looks good to me!

Maybe worth to backport to 3.x? For me it seems backwards compatible.

**Comment by clemensutschig** [comment]
@michaelsauter  - sure thing .. just want @tbugfinder to test this first 👍

**Comment by tbugfinder** [comment]
I couldn't get 17 retries while using:
```
odsComponentStageRolloutOpenShiftDeployment(context, [ deployTimeoutRetries: 17 ])

or

odsComponentStageRolloutOpenShiftDeployment(context, [ openshiftRolloutTimeoutRetries: 17 ])

```
I'm a little bit confused between the doc and the code.
Am I using appropriate setting?

**Comment by clemensutschig** [comment]
> odsComponentStageRolloutOpenShiftDeployment(context, [ deployTimeoutRetries: 17 ])

should do

**Comment by tbugfinder** [comment]
Excellent - works as expected (it finished successfully after 10 retries). Thank you.
Just a minor comment: as there are other timeouts (e.g. the build finish check) also using 12sec a user like myself might get on the wrong track. How about defaulting to 11sec or 13sec for this case?

**Pull request merged**
