### PR TITLE
Feature - support gitmodules (master)

### PR DESCRIPTION
**Pull request by SHoen**
This is a PR to discuss the ticket **Support of gitmodules #533**

Tested on a Repo with gitmodules and on one without gitmodules.

### CODE REVIEW

**Comment by clemensutschig** [comment]
@SHoen - cool. How do you use / invoke it.. ?

**Comment by SHoen** [comment]
@clemensutschig  
You have a .gitmodules file where you define the modules. 

For example two modules. You define the name, the path where it is linked in the "main" repo and ref to the repos of the modules.  
 The file looks like this->

 [submodule "libfoo"]
	path = include/foo
	url = git://foo.com/git/lib.git

[submodule "libbar"]
	path = include/bar
	url = git://bar.com/git/lib.git


With "branch" you can point to specific branches if you need.

**Comment by clemensutschig** [comment]
So no need for any configuration of the jenkinsfile? Very nice

**Comment by SHoen** [comment]
Yep, no need to change the jenkinsfile. If there is a .gitmodules file in the repo, it will init and update the modules. If you don't have one, it just do normal checkout.

**Review by clemensutschig — APPROVED** [review]

**Comment by clemensutschig** [comment]
@SHoen wonderfull

**Comment by michaelsauter** [comment]
@SHoen Nice!

There are some other places which checkout code, too:
```
→ ag GitSCM
vars/odsOrchestrationPipeline.groovy
70:            $class: 'GitSCM',

src/org/ods/orchestration/InitStage.groovy
453:            $class: 'GitSCM',

src/org/ods/services/GitService.groovy
137:            $class: 'GitSCM',
199:            $class: 'GitSCM',
```

Maybe have a look at them as well / unify it?

**Comment by metmajer** [comment]
@SHoen please consider @michaelsauter's advice. Otherwise, the Release Manager lacks support for Git submodules. Thanks for providing this fix, Steffen 👍

**Comment by SHoen** [comment]
@michaelsauter  I had a look into in. 

> → ag GitSCM
vars/odsOrchestrationPipeline.groovy
70:            $class: 'GitSCM',
-> adding the functionality would be helpful. 
     Localbranch extension is used, I need to investigate why this is not used in the gitservice.
    Perhaps it makes sense to add it there as well

src/org/ods/orchestration/InitStage.groovy
453:            $class: 'GitSCM',
-> checkout of Release manager repo ( support of gitmodules not necessary)
     I think usage of the gitservice would make sense anyway

src/org/ods/services/GitService.groovy
137:            $class: 'GitSCM',
199:            $class: 'GitSCM',
-> is used by the other components (most times with localbranch extension) except of  pipeline.groovy 
-> is used also in MRO Pipeline Util together with RelativeTargetDirectory and another time withLocalBranch

I will create a PR as proposal. Just need to figure out how to test the changes, especially with the release manager.

**Pull request merged**
