### PR TITLE
Refactor orchestration Project class

### LINKED ISSUE #292: Refactor orchestration Project class
The `Project` class is rather similar to the `Context` of the `component` and `quickstarter` packages. I think it would be good to rename `Project` to `Context`.

Further, once this is done, it would be nice to extract a new class (named `Project`) which deals with the project configuration (loading metadata etc.)

@metmajer Thoughts?

### PR DESCRIPTION
**Pull request by hrcornejo**
Closes #292 

- Renamed "Project" class to "Context" class
- Extracted utility to retrieve metadata, from "Context" class to a new "Project" class

### CODE REVIEW

**Comment by hrcornejo** [comment]
FYI @jorge-romero

**Comment by clemensutschig** [comment]
I am confused - I would have extracted all Jira specifics into a class, say 'Jira Project' - that would have inherited from a simple context object - that contains all the magic that is there even w/o jira ... 

for me - the change does not make too much sense right now, but maybe I just don't get it.

**Comment by hrcornejo** [comment]
@clemensutschig the change is not related with Jira. It just a rename of Project class and extract the functionality of read metadata (project metadata -repos, capabilities,... -) to a new class

**Comment by martsec** [comment]
Actually @hrcornejo now that we are at it, we could put the jira-related project details to a class that inherits from a more general "project" one.  And clean a bit the Project/Context part. What do you think? I have always found confusing the think of asking if the jira service is enabled or not.

**Comment by clemensutschig** [comment]
@martsec  - I totally agree,.. I would create a thin context (that has all NO jira pieces in there ..) and a JiraContext? that has all the jira magic in it ... then we initialize once the right guy and are done :)

**Comment by metmajer** [comment]
@martsec @hrcornejo @clemensutschig there is definitely a range of concerns being covered in this class. Renaming alone won't cut it. Let's do this right please and separate those concerns if your goal is to create clean code :)

**Comment by hrcornejo** [comment]
Move the discussion to the issue

**Comment by metmajer** [comment]
Closing for inactivity. Needs a structured approach with a clear separation of concerns.

**Pull request closed without merging**
