### PR TITLE
Fix ArrayList error in Orchestration pipeline

### PR DESCRIPTION
**Pull request by braisvq1996**
Fix for #745

### CODE REVIEW

**Comment by metmajer** [comment]
@clemensutschig @braisvq1996 @s2oBCN @jorge-romero just a thought, guys... what if we create `Util.findAll` etc. methods with a "safe" implementation? This would improve code readability and would not require vast changes to existing codebase.

**Comment by metmajer** [comment]
@braisvq1996 can you please fix the CodeNarc errors? Which are the results from your tests? Do the fixes show good effects?

**Comment by braisvq1996** [comment]
@metmajer , with this changes the serialization issue does not seems to appear anymore, bue we do get ``Hit Jenkins serialization issue, attempt X`` in the Jenkins pipeline log.
I will fix the CodeNarc errors as soon as I can

**Comment by clemensutschig** [comment]
@metmajer seems its working fine :) I also took a look at another project which shows similar errors - and the code we have put in place now should fix those (Even on 3.x) @s2oBCN

**Comment by metmajer** [comment]
Very cool @braisvq1996 and @clemensutschig! I would fix the CodeNarc issues myself, but I don't have access to Brais' branch.

**Comment by metmajer** [comment]
Colleagues, until Brais' branch is merged into ODS' fix branch, I want to document the approach here. The benefits of using utility methods is that...
a) these methods can be easily Unit tested. Unit tests would need to prove that, basically `java.util.Collection.findAll(...) == `Util.findAll(collection,...)`.
b) Changes to the codebase remain surgical, since methods from Java can be easily replaced with our utility methods. This helps in code reviews to assert that changes do not introduce failure.

**Comment by clemensutschig** [comment]
super nice @metmajer  - the only thing we need to do is to remove the NonCPS annotations - because if you take a look, we use plenty of script..... in there

**Pull request merged**
