### PR TITLE
Rename release branch to release/${version} (#471)

### PR DESCRIPTION
**Pull request by felipecruz91**
* Renamed release branch to release/${version}

* Distinguis between ODS_GIT_TAG_PREFIX and ODS_GIT_BRANCH_PREFIX

* Updated documentation

* Fixed CodeNarc rule violation

* Added test for getReleaseBranch method

Co-authored-by: zxBCN Cruz_Martinez <felipe.cruz_martinez.ext@boehringer-ingelheim.com>

### CODE REVIEW

**Comment by felipecruz91** [comment]
@metmajer This is the `git cherry-pick` for the `3.x` branch.

**Comment by michaelsauter** [comment]
The description says:

> Renamed release branch to release-ods-generated/${version}

But now it's actually `release/${version}`, right?

**Comment by felipecruz91** [comment]
> The description says:
> 
> > Renamed release branch to release-ods-generated/${version}
> 
> But now it's actually `release/${version}`, right?

@michaelsauter The description was reflecting one of the commit messages that I pushed when it was agreed to change the branch name to release-ods-generated/${version}. However, afterwards, it was decided to keep the `release/${version}` branch name.

I've amended the description to match the final decision.

**Review by metmajer — APPROVED** [review]
Thanks @felipecruz91!

**Comment by metmajer** [comment]
@felipecruz91 ready to merge!

**Pull request merged**
