### PR TITLE
find repoName dynamically - master

### LINKED ISSUE #417: Do not hardcode repoName (project & componentId) - rather than from origin git url
https://github.com/opendevstack/ods-document-generation-svc/blob/master/Jenkinsfile#L20

Falls with:

OpenShift Build unitt-cd/run-documentgensvc-unitt-master-1 from http://bitbucket.odsbox.lan:7990/scm/unitt/documentgensvc.git
Checking out git http://bitbucket.odsbox.lan:7990/scm/unitt/documentgensvc.git into /var/lib/jenkins/jobs/unitt-cd/jobs/unitt-cd-run-documentgensvc-unitt-master/workspace@script to read Jenkinsfile
using credential unitt-cd-cd-user-with-password
Cloning the remote Git repository
Cloning repository http://bitbucket.odsbox.lan:7990/scm/unitt/documentgensvc.git
 > git init /var/lib/jenkins/jobs/unitt-cd/jobs/unitt-cd-run-documentgensvc-unitt-master/workspace@script # timeout=10

.......

SonarQube Analysis-documentgensvc] **** STARTING stage 'SonarQube Analysis' for component 'documentgensvc' branch 'master' ****
[Pipeline] stage
[Pipeline] { (SonarQube Analysis)
[Pipeline] echo
Scanned branches: *
[Pipeline] echo
Long-lived branches: master
[Pipeline] readProperties
[Pipeline] withCredentials
Masking supported pattern matches of $USERNAME or $TOKEN
[Pipeline] {
[Pipeline] sh
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep': label
Curl --fail --silent --header 'Authorization: Bearer ****' 'http://bitbucket.odsbox.lan:7990/rest/api/1.0/projects/unitt/repos/unitt-documentgensvc/pull-requests?state=OPEN'
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
[SonarQube Analysis-documentgensvc] **** ENDED stage 'SonarQube Analysis' for component 'documentgensvc' branch 'master' **** (took 522 ms)
[Pipeline] }
[Pipeline] // wrap
[Pipeline] stage
[Pipeline] { (odsPipeline error)
[Pipeline] echo
WARN: [documentgensvc] ***** Finished ODS Pipeline for documentgensvc (with error) ***** (took 182670 ms)
[Pipeline] echo
WARN: Error: hudson.AbortException: script returned exit code 22

Which seems to be *unauthorized*
All other quickstarters provisioned.. which also use sq do not have this issue.. (and no pr Check, which leads me to believe sth is wrong with the pr Check curl call)

@georgfedermann fyi

### PR DESCRIPTION
**Pull request by clemensutschig**
fwd port to close #417  for master

### CODE REVIEW

**Review by michaelsauter — APPROVED** [review]
I like it 👍. However I don't know if there aren't any other surprises further down :/

**Comment by clemensutschig** [comment]
@michaelsauter  - I quickly checked the codebase - and there should NOT be any effects ...

**Comment by SHoen** [comment]
Hi @clemensutschig @michaelsauter,
I'm getting the following error on some project. On 3.x it still works. It looks like that repoName on Pipeline.groovy:395 is not defined.
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: repoName for class: org.ods.component.Pipeline
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at org.ods.component.Pipeline.amendProjectAndComponentFromOrigin(Pipeline.groovy:395)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at jdk.internal.reflect.GeneratedMethodAccessor300.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE

**Comment by SHoen** [comment]
@clemensutschig @michaelsauter #584 should solve the issue. At least it works for my component

**Pull request merged**
