### PR TITLE
Fix document history in cftp

### PR DESCRIPTION
**Pull request by jorge-romero**
Remove not needed entries in the document history of the document cftp

### CODE REVIEW

**Comment by metmajer** [comment]
@jorge-romero what is the purpose of this PR? The FTP needs to list all test cases. This change removes the references to the test cases and therefore they will not be printed in the FTP document.

**Comment by jorge-romero** [comment]
> @jorge-romero what is the purpose of this PR? The FTP needs to list all test cases. This change removes the references to the test cases and therefore they will not be printed in the FTP document.

@metmajer Currently CFTP only has descriptive information that is obtained of the Documentation Chapters. The test cases exists in the CFTR document, with this changes we remove the not needed information regarding tests in json, that includes the information in the data area and the history area of the method output.

**Comment by jorge-romero** [comment]
@metmajer Confirmed the last coment, it is not needed to add the references of the tests, this document works as a test strategy, not a test plan

**Comment by metmajer** [comment]
@jorge-romero please resolve conflicts and I will approve.

**Review by s2oBCN — APPROVED** [review]

**Comment by metmajer** [comment]
@s2oBCN @jorge-romero please also merge into 4.x

**Pull request merged**
