### PR TITLE
fix: add resource cpu to container template

### PR DESCRIPTION
**Pull request by SimonGolms**
specify cpu and memory for resource requests, otherwise the slave will try to reserve all available cpu
- set request cpu to 10 millicores
- set limit cpu to 300 millicores

### CODE REVIEW

**Comment by michaelsauter** [comment]
@SimonGolms How did you come up with the specific values?

**Comment by SimonGolms** [comment]
10m; to stay alive
300m: best practice / randomly

If you need a custom jenkins slave, you will probably need other resource requirements as well. the information is therefore only used as fallback to avoid unnecessary stress on the cluster.

How did you calculate the memory specifications? Feel free to adjust the values according to your own preferences.

**Comment by michaelsauter** [comment]
@SimonGolms Thanks for the explanation. The memory values are based on the "worst" quickstarters (e.g. Angular needs for its production build 2Gi). This should be adjusted in the future to have those values appropriate for the quickstarters and easier to modify for users.

**Comment by michaelsauter** [comment]
@rattermeyer Can you have a look at this as well?

**Comment by michaelsauter** [comment]
Moving this to v3.

On some clusters, 50m seems to be the minimum. Further, some slaves might need more than 300m to run at a reasonable speed. 

We probably need sth. that is configurable, and specific for each type of quickstarter.

**Comment by michaelsauter** [comment]
Closing this in favour of #175.

**Pull request closed without merging**
