### PR TITLE
Adds aqua stage partial page to component-pipeline page

### LINKED ISSUE #796: component-pipeline doc page does not include aqua stage
On the [page where all component stages are listed](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/docs/modules/jenkins-shared-library/pages/component-pipeline.adoc) the [partial doc page about aqua](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithAqua.adoc) is not included.

### PR DESCRIPTION
**Pull request by renedupont**
closes #796

### CODE REVIEW

**Comment by metmajer** [comment]
@renedupont @hrcornejo I believe that some of the contents in https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithAqua.adoc are outdated.

**Comment by renedupont** [comment]
@metmajer hm yes I guess that is the status of the stage when I sort of handed it over. Would you know who knows best what was changed afterwards and is able to update it?

**Review by gerardcl — APPROVED** [review]
LGTM! 

I would merge this one and fix what @metmajer comments with its specific issue, is that ok?

**Comment by metmajer** [comment]
Please let @hrcornejo have a look. The current content is not accurate.

**Comment by hrcornejo** [comment]
@metmajer updated doc in #803

**Comment by renedupont** [comment]
@hrcornejo the change made in this PR is still required to show the page you updated. Shall I merge it?

**Comment by hrcornejo** [comment]
@renedupont yes

**Review by hrcornejo — APPROVED** [review]

**Pull request merged**
