### PR TITLE
WIP: Improve check whether branch should be checked by SonarQube or not

### PR DESCRIPTION
**Pull request by michaelsauter**
Keeping this in WIP until we resolve if we continue with the config file in the Jenkins Master.

FYI @oalyman

### CODE REVIEW

**Comment by michaelsauter** [comment]
This should probably replace the solution implemented for https://github.com/opendevstack/ods-jenkins-shared-library/issues/213.

**Comment by clemensutschig** [comment]
@michaelsauter  - shouldnt this now be closed with all the work you have done on SQ?

**Comment by michaelsauter** [comment]
@clemensutschig No, this is slightly different.

The SQ work that is in master allows to decorate pull requests, but the feature is not automatically enabled yet. To enable it, one has to set `branch: '*'`.

This PR resolved, based on the config baked into the Jenkins Master image, whether all branches should be scanned. As a result, scanning would be seamless = on by default when supported, off by default when not supported.

BUT there has been discussion about pushing the Jenkins Master image to Docker Hub / GitHub (https://github.com/opendevstack/ods-core/issues/491), and that would prevent putting the config file into the image.

I want to wait a little to see what we want to do regarding image pushing for 3.0, and then come back to this if still applicable.

**Comment by clemensutschig** [comment]
@michaelsauter - with the current work, I think we are ok to leave this as is .. what do you think?

**Comment by michaelsauter** [comment]
Given that we will not push the Jenkins images to Docker Hub / GitHub, I think it would be nice to complete this. It gives you auto-configuration which branches should be scanned, based on the SQ installation.

**Comment by michaelsauter** [comment]
To avoid problems in the future, I'll not pursue this any further. Config file will be removed in https://github.com/opendevstack/ods-core/pull/590.

**Pull request closed without merging**
