### PR TITLE
Removes DIL_P doc.

### PR DESCRIPTION
**Pull request by victorpablosceruelo**
DIL (Discrepance Log) is a document that should not be generated when going to Production ( DIL_P ).
This PR is to remove it.

### CODE REVIEW

**Review by clemensutschig — CHANGES_REQUESTED** [review]
QA approved?

**Comment by victorpablosceruelo** [comment]
> QA approved?

No, QA has not approved it.
Still work in progress. Sorry, I forgot to put it in WIP status.

**Comment by victorpablosceruelo** [comment]
We changed the base (target) branch to feature/flexible_r2p_jira_workflow
because this is part of a bigger task and all needs to go in a single PR.
Nevertheless, this subtask is still under revision.

**Comment by victorpablosceruelo** [comment]
We need to merge this "remove DIL_P doc" to continue with the development process.
Although we are not doing merge to master, I ask for your reviews before doing it (to know if we can continue or not)
@jafarre-viewnext @jorge-romero @angelmp01 @metmajer @clemensutschig 

Thanks!!

**Review by metmajer — APPROVED** [review]

**Pull request merged**
