### PR TITLE
Fix Traceability matrix to not show Unit tests to branch master

### PR DESCRIPTION
**Pull request by hrcornejo**
Only Acceptance, Integration and Installation test must be shown in Traceability matrix. See #799

### CODE REVIEW

**Comment by hrcornejo** [comment]
@s2oBCN the failing tests are not related to changes. The fail occurs creating temp files to SonarQube tests and work properly in local.

**Comment by hrcornejo** [comment]
@michaelsauter the action build is failing in test that create a temp file. Some examples:
`
java.io.IOException: No such file or directory
	at java.io.File.createTempFile(File.java:2063)
	at java.io.File.createTempFile(File.java:2109)
	at org.ods.component.ScanWithSonarStageSpec.archive report in Nexus(ScanWithSonarStageSpec.groovy:67)
`
`
java.io.IOException: No such file or directory
	at java.io.File.createTempFile(File.java:2063)
	at java.io.File.createTempFile(File.java:2109)
	at org.ods.component.ScanWithSonarStage.generateTempFileFromReport(ScanWithSonarStage.groovy:271)
	at org.ods.component.ScanWithSonarStage.run(ScanWithSonarStage.groovy:105)
	at org.ods.component.Stage.execute_closure2(Stage.groovy:33)
	at org.ods.component.Stage.execute_closure2(Stage.groovy)
`
The tests works fine in local. Is there any problems with temp files in this build actions?

**Comment by michaelsauter** [comment]
> The tests works fine in local. Is there any problems with temp files in this build actions?

Nothing in particular that I am aware of :(

Are there maybe any other places where temp files are used and it works?

**Comment by hrcornejo** [comment]
@michaelsauter I've no idea, but is very strange. Other PR #803 based in master branch and with only doc changes, has the same behaviour 7 test failing trying to create temp files.

**Comment by renedupont** [comment]
fyi I created #806 to tackle the failing tests issue

**Pull request merged**
