### PR TITLE
Feature/test summary for empty description (#816) - 4.x

### PR DESCRIPTION
**Pull request by jorge-romero**
* Use test summary in case test description is empty

### CODE REVIEW

**Review by s2oBCN — APPROVED** [review]

**Comment by metmajer** [comment]
@jorge-romero @s2oBCN this should have been in the current release, but is still not merged?

**Review by clemensutschig — APPROVED** [review]

**Comment by clemensutschig** [comment]
must go into master as well

**Comment by clemensutschig** [comment]
please merge

**Comment by metmajer** [comment]
@jorge-romero @jafarre-viewnext ping

**Comment by jorge-romero** [comment]
Code is both in master and 4.x, this PR I don't know why it was kept open

**Pull request closed without merging**
