### PR TITLE
Linked to #454

### PR DESCRIPTION
**Pull request by borja44**
bugfix docgen automatic generation for docgen unitest

### CODE REVIEW

**Review by metmajer — APPROVED** [review]

**Comment by metmajer** [comment]
@jorge-romero @borja44 please make sure this also gets fixed in the master branch! Target branch here is only 3.x.

**Review by metmajer — CHANGES_REQUESTED** [review]
@borja44 @jorge-romero can you please explain why this resolution fixes the issue? You have added @NonCPS annotations to code that should not need it anyway. Do you have proof that documents are now correctly rendered?

**Comment by jafarre-viewnext** [comment]
> @borja44 @jorge-romero can you please explain why this resolution fixes the issue? You have added @NonCPS annotations to code that should not need it anyway. Do you have proof that documents are now correctly rendered?

@metmajer Jairo explained to me that the fix comes originally from Martí. Apparently, the CPS environment is not totally compatible with standard Groovy and this causes the observed problems. Martí provided the following links:

https://stackoverflow.com/questions/42295921/what-is-the-effect-of-noncps-in-a-jenkins-pipeline-script
https://www.jenkins.io/doc/book/pipeline/cps-method-mismatches/
https://www.jenkins.io/doc/book/pipeline/cps-method-mismatches/#calling-non-cps-transformed-methods-with-cps-transformed-arguments

Jairo and @borja44 just cherry-picked the changes by Martí and I helped fix the format-validation issues.
The fix has been tested by Jairo.

**Comment by metmajer** [comment]
@borja44 @jafarre-viewnext @jorge-romero the differences between CPS and Groovy are documented with Jenkins. Would be good to create some awareness in the team by doing a presentation, etc. Thanks for the fix!

**Comment by stitakis** [comment]
@borja44 @metmajer @michaelsauter was this fix ported to master?

**Comment by michaelsauter** [comment]
@stitakis good catch, I don't think it was. @borja44 can you open a PR against master as well? Thanks!

**Comment by metmajer** [comment]
@stitakis @michaelsauter @borja44 this fix was cherry-picked from an open PR that is supposed to go to master

**Comment by stitakis** [comment]
thanks @metmajer for the info...
@jafarre-viewnext @borja44 to double check, which is the open PR that is supposed to go to master? I'm asking because I can find it

**Comment by metmajer** [comment]
@stitakis my bad, you are right... https://github.com/opendevstack/ods-jenkins-shared-library/pull/446 points at 3.x. Sadly, this PR has become huge. I suggest migrating #446 also to master once finished.

**Pull request merged**
